PFLAGS += -Fi$(FPGUI)/src
PFLAGS += -Fi$(FPGUI)/src/corelib
PFLAGS += -Fu$(FPGUI)/src/corelib
PFLAGS += -Fi$(FPGUI)/src/corelib/x11
PFLAGS += -Fu$(FPGUI)/src/corelib/x11
PFLAGS += -Fu$(FPGUI)/src/gui
PFLAGS += -Fu$(FPGUI)/src/3rdparty/regex

PFLAGS += -Fi$(FPGUI)/src/corelib/render/software
PFLAGS += -Fu$(FPGUI)/src/corelib/render/software
PFLAGS += -Fu$(FPGUI)/src/corelib/render/software/platform/linux
PFLAGS += -Fu$(FPGUI)/src/corelib/render/software/ctrl
PFLAGS += -Fu$(FPGUI)/src/corelib/render/software/util

PFLAGS += -dAGGCanvas
